In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("../data/raw/annual-population-growth/annual-population-growth.csv")

In [3]:
df.head()

,Entity,Code,Year,Annual change in population,Annual population change (Projected)
0,Afghanistan,AFG,1951,103163.0,NaN
1,Afghanistan,AFG,1952,108441.0,NaN
2,Afghanistan,AFG,1953,108919.0,NaN
3,Afghanistan,AFG,1954,111251.0,NaN
4,Afghanistan,AFG,1955,119027.0,NaN

In [4]:
df.shape

(38400, 5)

In [5]:
df.columns.tolist()

['Entity',
 'Code',
 'Year',
 'Annual change in population',
 'Annual population change (Projected)']

In [6]:
df.dtypes

Entity                                      str
Code                                        str
Year                                      int64
Annual change in population             float64
Annual population change (Projected)    float64
dtype: object

In [7]:
df.describe()

,Year,Annual change in population,Annual population change (Projected)
count,38400.000000,1.868800e+04,1.971200e+04
mean,2025.500000,2.063019e+06,8.375481e+05
std,43.300872,9.440859e+06,5.816745e+06
min,1951.000000,-3.315935e+06,-2.291035e+07
25%,1988.000000,1.781000e+03,-9.742750e+03
50%,2025.500000,4.689800e+04,9.350000e+01
75%,2063.000000,3.021128e+05,1.411160e+05
max,2100.000000,9.337137e+07,7.206736e+07

In [8]:
df.isnull().sum()

Entity                                      0
Code                                     1200
Year                                        0
Annual change in population             19712
Annual population change (Projected)    18688
dtype: int64

In [9]:
df["Entity"].nunique()

256

In [10]:
df_year= df ["Year"]
df_year.head()

0    1951
1    1952
2    1953
3    1954
4    1955
Name: Year, dtype: int64

In [11]:
df_extraccion_columnas= df[["Entity", "Year"]]
df_extraccion_columnas.head()

        Entity  Year
0  Afghanistan  1951
1  Afghanistan  1952
2  Afghanistan  1953
3  Afghanistan  1954
4  Afghanistan  1955

In [12]:
df_extraccion_filas = df[df["Year"] == 2020]
df_extraccion_filas.head()

,Entity,Code,Year,Annual change in population,Annual population change (Projected)
69,Afghanistan,AFG,2020,1212852.0,NaN
219,Africa (UN),UN_AFR,2020,32815675.0,NaN
369,Albania,ALB,2020,-13061.0,NaN
519,Algeria,DZA,2020,747543.0,NaN
669,American Samoa,ASM,2020,-451.0,NaN

In [13]:
df_2020_mex = df[(df["Year"] == 2020) & (df["Entity"] == "Mexico")]   
df_2020_mex.head()

,Entity,Code,Year,Annual change in population,Annual population change (Projected)
22269,Mexico,MEX,2020,1036075.0,NaN

In [14]:
df_2004_2020 = df[(df["Year"] >= 2004) & (df["Year"] <=2020) & (df["Entity"] == "Mexico")]
df_2004_2020.head()

,Entity,Code,Year,Annual change in population,Annual population change (Projected)
22253,Mexico,MEX,2004,1415614.0,NaN
22254,Mexico,MEX,2005,1417373.0,NaN
22255,Mexico,MEX,2006,1442162.0,NaN
22256,Mexico,MEX,2007,1520690.0,NaN
22257,Mexico,MEX,2008,1599930.0,NaN

In [15]:
df_mex = df_2004_2020[["Entity", "Year", "Annual change in population"]]
df_mex.head()

       Entity  Year  Annual change in population
22253  Mexico  2004                    1415614.0
22254  Mexico  2005                    1417373.0
22255  Mexico  2006                    1442162.0
22256  Mexico  2007                    1520690.0
22257  Mexico  2008                    1599930.0

In [16]:
df_mex.mean(numeric_only=True)

Year                              2012.0
Annual change in population    1401208.0
dtype: float64

In [17]:
df.iloc[:, 0:2]

            Entity Code
0      Afghanistan  AFG
1      Afghanistan  AFG
2      Afghanistan  AFG
3      Afghanistan  AFG
4      Afghanistan  AFG
...            ...  ...
38395     Zimbabwe  ZWE
38396     Zimbabwe  ZWE
38397     Zimbabwe  ZWE
38398     Zimbabwe  ZWE
38399     Zimbabwe  ZWE

[38400 rows x 2 columns]

In [18]:
df.loc[10000]

Entity                                  Equatorial Guinea
Code                                                  GNQ
Year                                                 2051
Annual change in population                           NaN
Annual population change (Projected)              46407.0
Name: 10000, dtype: object

In [19]:
df.loc[:, ["Entity", "Year", "Annual change in population"]]

            Entity  Year  Annual change in population
0      Afghanistan  1951                     103163.0
1      Afghanistan  1952                     108441.0
2      Afghanistan  1953                     108919.0
3      Afghanistan  1954                     111251.0
4      Afghanistan  1955                     119027.0
...            ...   ...                          ...
38395     Zimbabwe  2096                          NaN
38396     Zimbabwe  2097                          NaN
38397     Zimbabwe  2098                          NaN
38398     Zimbabwe  2099                          NaN
38399     Zimbabwe  2100                          NaN

[38400 rows x 3 columns]

In [ ]:
df.loc[df_2020_mex.index, :]

In [30]:
df.iloc[0:5]

,Entity,Code,Year,Annual change in population,Annual population change (Projected)
0,Afghanistan,AFG,1951,103163.0,NaN
1,Afghanistan,AFG,1952,108441.0,NaN
2,Afghanistan,AFG,1953,108919.0,NaN
3,Afghanistan,AFG,1954,111251.0,NaN
4,Afghanistan,AFG,1955,119027.0,NaN

In [34]:
df.iloc[:, [0,2,3]]

            Entity  Year  Annual change in population
0      Afghanistan  1951                     103163.0
1      Afghanistan  1952                     108441.0
2      Afghanistan  1953                     108919.0
3      Afghanistan  1954                     111251.0
4      Afghanistan  1955                     119027.0
...            ...   ...                          ...
38395     Zimbabwe  2096                          NaN
38396     Zimbabwe  2097                          NaN
38397     Zimbabwe  2098                          NaN
38398     Zimbabwe  2099                          NaN
38399     Zimbabwe  2100                          NaN

[38400 rows x 3 columns]

In [ ]:
df.iloc[0:5      , 0:3]

        Entity Code  Year
0  Afghanistan  AFG  1951
1  Afghanistan  AFG  1952
2  Afghanistan  AFG  1953
3  Afghanistan  AFG  1954